language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - DEFAULT=1

install:
  - composer self-update
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"

notifications:
  email: false
